
services:
  agent-a:
    build: ./agent-a
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
    depends_on:
      - agent-b

  agent-b:
    build: ./agent-b
    ports:
      - "8001:8001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  ui:
    build: ./ui
    ports:
      - "8501:8501"
    depends_on:
      - agent-a
