# k8s/agent-a-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-a
  template:
    metadata:
      labels:
        app: agent-a
    spec:
      containers:
      - name: agent-a
        image: legacycoder777/video_summarizer_using_gemini-agent-a:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: agent-a-service
spec:
  selector:
    app: agent-a
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
